### PR TITLE
fix success exit code

### PR DESCRIPTION
**Pull request by a-x-**
if i attempt put c2s into shell pipe, then i'll give surprise.

### CODE REVIEW

**Comment by dciccale** [comment]
what does this changes?

**Comment by a-x-** [comment]
Fix this case: `c2s style.css && echo TaDa`

**Comment by dciccale** [comment]
i don't understand, where is the issue?

`style.css`
```css
body {
  color: red;
}
```

```sh
$ css2stylus style.css && echo TaDa
Processing style.css ...
Output saved to: style.styl
```

`style.styl`
```css
body
  color red
```

**Comment by dciccale** [comment]
could you rebase this branch so i can merge it?

**Comment by a-x-** [comment]
Done

**Pull request merged**
