### PR TITLE
bump yargs version

### PR DESCRIPTION
**Pull request by a-x-**

### CODE REVIEW

**Comment by dciccale** [comment]
what improvement is this giving?

**Comment by a-x-** [comment]
as `yargs` maintainer said to me, it fix opts' type settings.

**Comment by a-x-** [comment]
but i didn't detect explicit improvements/problems.

**Comment by a-x-** [comment]
see thread also: https://github.com/bcoe/yargs/issues/212

**Comment by dciccale** [comment]
ok, is merged already thanks for your contribution!

**Pull request merged**
